.\"                                      Hey, EMACS: -*- nroff -*-
.\" First parameter, NAME, should be all caps
.\" Second parameter, SECTION, should be 1-8, maybe w/ subsection
.\" other parameters are allowed: see man(7), man(1)
.TH WMCCCC 1 "september 3, 2002" "[0iN <o|n" "WMcoincoin manual"
.\" Please adjust this date whenever revising the manpage.
.\"
.\" Some roff macros, for reference:
.\" .nh        disable hyphenation
.\" .hy        enable hyphenation
.\" .ad l      left justify
.\" .ad b      justify to both left and right margins
.\" .nf        disable filling
.\" .fi        enable filling
.\" .br        insert line break
.\" .sp <n>    insert n+1 empty lines
.\" for manpage-specific macros, see man(7)
.SH NAME
wmccc \- WMCoinCoin Configurator
.SH SYNOPSIS
.B wmccc
.RI [\| filename \|]
.SH DESCRIPTION
This manual page documents briefly the
.B wmccc
command.
This manual page was written for the Debian distribution
because the original program does not have a manual page.
.P
WMCCC is a GTK+ tool to help in the configuration of
.BR wmcoincoin (1).
It creates a new configuration file in
.I $HOME/.wmcoincoin
or edits
.I $HOME/.wmcoincoin/filename
if
.I filename
is given as an argument, showing options in a graphical way.
.SH SEE ALSO
.BR wmcoincoin (1)
.SH AUTHOR
This manual page was written by Josselin Mouette <joss@debian.org>,
for the Debian GNU/Linux system (but may be used by others).
.PP
The original software was written by Julien Pommier <c0in@altern.org>.
